"""Read C/header sources only; index pad readers and every map event table.

No disc, binary, extracted asset, assembly, message strings or screenshots read.
The output contains names/locations/counts, never game data or C source bodies.
"""
from pathlib import Path
import argparse
import re
import subprocess

args = argparse.ArgumentParser()
args.add_argument("reference", type=Path)
args.add_argument("--check", action="store_true")
opt = args.parse_args()
root = Path(__file__).resolve().parents[1]
reference = opt.reference.resolve()
commit = subprocess.check_output(["git", "-C", str(reference), "rev-parse", "HEAD"], text=True).strip()
readers = []
callbacks = []
files = list((reference / "src").rglob("*.c")) + list((reference / "src").rglob("*.h"))
for path in sorted(files):
    lines = path.read_text(encoding="utf8").splitlines()
    function = "global / conditional include"
    functions = {}
    for number, line in enumerate(lines, 1):
        match = re.match(r"^(?:static\s+)?(?:void|bool|s32|s16|u32|q\w+|[su]_\w+\*?)\s+(\w+)\([^;]*\)(?:\s*//.*)?$", line)
        if match:
            function = match.group(1)
        if re.search(r"g_Controller[01]\b|\bPad(?:InitDirect|StartCom|GetState|InfoMode|SetActAlign|SetAct|SetMainMode|InfoAct)\s*\(", line):
            functions.setdefault(function, []).append(number)
    for function, numbers in functions.items():
        readers.append((path.relative_to(reference).as_posix(), function, numbers))
    text = "\n".join(lines)
    match = re.search(r"g_MapEventFuncs\[\]\)\(\)\s*=\s*\{(.*?)\};", text, re.S)
    if match:
        body = re.sub(r"/\*.*?\*/|//[^\n]*", "", match.group(1), flags=re.S)
        names = re.findall(r"\b(?:MapEvent_\w+|func_\w+|sharedFunc_\w+)\b", body)
        callbacks.append((path.relative_to(reference).as_posix(), names))

def route(path, function):
    if "libkpad" in path:
        return "Controller handshake/vibration only; joy.c consumes raw bytes"
    if path.endswith("joy.c"):
        return "PS1 packet, active-low bits, analog thresholds; pad packet tests"
    if "map1_s01" in path and function == "PianoPuzzle_Control":
        return "piano_white / piano_black / puzzle_cancel"
    if "map3_s03" in path and function == "func_800D1A58":
        return "plates_insert / plates_remove / puzzle_cancel"
    if "map5_s01" in path:
        return "motel_digits/enter/clear or safe_ring/left/right; puzzle_cancel"
    if "map7_s01" in path and function == "func_800D94DC":
        return "nowhere_letters_a / puzzle_cancel"
    if "map7_s01" in path and function == "func_800D9C9C":
        return "nowhere_lights_a / puzzle_cancel"
    if "map7_s02" in path and function == "func_800E32E0":
        return "nowhere_letters_b / puzzle_cancel"
    if "map7_s02" in path and function == "func_800DFDDC":
        return "nowhere_lights_b / puzzle_cancel"
    if "map1_s04" in path or "gfx/bodyprog_800652F4" in path:
        return "sound_test, raw_*; unused/debug consumers"
    if "vc_util" in path:
        return "look + labelled raw pad/axis targets; secondary-controller debug camera uncertain"
    if "maps/" in path:
        return "cutscene_skip / dialogue_next / dialogue_cancel; debug raw_r3 if applicable"
    if "player_control" in path:
        return "Movement / step / aim / attack / action rows"
    if "item_screens" in path:
        return "Inventory item/operation/scroll/rotate/close rows"
    if "mapscreen" in path:
        return "Map pan/floor/close/toggle + map_projection"
    if "options" in path:
        return "option_* / options_extra / menu_confirm/back"
    if "saveload" in path:
        return "save_* / load_slot"
    if "title" in path:
        return "title_* / difficulty"
    if "warm_boot" in path:
        return "warm_reset / return_title"
    if "game_sys_states" in path:
        return "flashlight/map/inventory/pause/unpause/game_over/debug_save"
    if "map_msg_display" in path or "events_util" in path:
        return "dialogue_next/choice/cancel; item-use and switch puzzles"
    if "events_main" in path:
        return "interact / pickup / all_keys"
    if "screens/" in path:
        return "boot_continue / cutscene_skip / credits"
    return "Lifecycle/demo/controller plumbing; host pad packet; no separate gameplay input"

output = f"""# Independent source input audit

Reference commit: `{commit}`. Generated by `tools/audit_reference.py` from C/header
source only. Includes conditional/non-USA/debug sites for visibility; they are not
automatically enabled. US defaults and bits were read in `settings_reset.c` and
`include/bodyprog/sys/joy.h`; low-level status, type and actuator handling was read
in `src/bodyprog/libkpad/libkpad.c`. Its `func_8009E198` is still INCLUDE_ASM; this
crate does not claim to replace that controller init/vibration function.

Scan: {len(files)} C/header files, {len(readers)} pad-consumer function entries,
{len(callbacks)} event tables, {sum(len(names) for _, names in callbacks)} callback entries.
This inventories direct readers, not a proof of every possible indirect/runtime
path. Unnamed callbacks retain a touch route through action, inventory Use and
direct message/choice targets, plus labelled pad fallback if a legacy panel needs
it. Scene identities, target IDs and exact host adapters remain integration work.

## Direct pad consumers

| Source | Function | Input read lines | Covered path |
| --- | --- | --- | --- |
"""
for path, function, numbers in readers:
    output += f"| `{path}` | `{function}` | {', '.join(map(str, numbers))} | {route(path, function)} |\n"
output += "\n## All map-event callback tables\n\nEach table retains its entire callback list, including anonymous and shared events.\nThe common action/item-use/message paths cover interaction; detailed unidentified\nsemantics are explicitly uncertain (COVERAGE row `unidentified_events`).\n\n"
for path, names in callbacks:
    output += f"- `{path}` ({len(names)}): " + (", ".join(f"`{name}`" for name in names) if names else "empty event table") + "\n"
target = root / "INPUT_AUDIT.md"
if opt.check:
    if not target.exists() or target.read_text(encoding="utf8") != output:
        raise SystemExit("input audit differs: regenerate and review against this reference revision")
    print("Reference audit matches checked-in source inventory")
else:
    target.write_text(output, encoding="utf8")
    print(f"Indexed {len(files)} files; {len(readers)} pad consumers; {len(callbacks)} callback tables")
